name: Build project

on: [push]

jobs:
    build:
        name: DUB Build
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                dc: [dmd-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v1

            - name: Install D compiler
              uses: mihails-strasuns/setup-dlang@v0.3.0
              with:
                  compiler: ${{ matrix.dc }}

            - name: Build
              run: dub build --force --build-mode=singleFile -v

            - name: Create bin dir
              run: mkdir -p bin/${{runner.os}}

            - name: Move executable
              if: runner.os != 'Windows'
              run: mv xcbasic64 bin/${{runner.os}}/xcbasic64
              shell: bash
              
            - name: Move executable (win)
              if: runner.os == 'Windows'
              run: mv xcbasic64.exe bin/${{runner.os}}/xcbasic64.exe
              shell: bash
              
            - name: Commit files
              run: |
                 git config --local user.email "action@github.com"
                 git config --local user.name "GitHub Action"
                 git commit -m "Added latest binaries" -a

            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                 github_token: ${{ secrets.GITHUB_TOKEN }}
