name: Build project

on: [push]

jobs:
    build:
        name: DUB Build
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                dc: [dmd-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v1

            - name: Install D compiler
              uses: mihails-strasuns/setup-dlang@v0.3.0
              with:
                  compiler: ${{ matrix.dc }}

            - name: Build
              run: dub build --force --build-mode=singleFile -v

	    - name: Zip_windows
	      uses: montudor/action-zip@v0.1.0
	      if: runner.os == "Windows"
	      with:
	    	  args: zip -qq -r ./xcb.zip ./xcbasic64.exe

	    - name: Zip_non-windows
	      uses: montudor/action-zip@v0.1.0
	      if: runner.os != "Windows"
	      with:
	        args: zip -qq -r ./xcb.zip ./xcbasic64

	    - name: Upload
	      uses: Shopify/upload-to-release
	      with:
    	    	  name: xcbasic64_${{runner.os}}.zip
            	  path: ./xcb.zip
        	  repo-token: ${{ secrets.GITHUB_TOKEN }}